### ISSUE TITLE
pin mux in dts 

### ISSUE THREAD

**Issue by Tibalt** [martingkelly/nunchuk#1]
i2c1_pins: pinmux_i2c1_pins {
pinctrl-single,pins = <
AM33XX_IOPAD(0x158, PIN_INPUT_PULLUP | MUX_MODE2) /* spi0_d1.i2c1_sda */
AM33XX_IOPAD(0x15c, PIN_INPUT_PULLUP | MUX_MODE2) /* spi0_cs0.i2c1_scl */
>;
};

In the above part, I believe the control module register address should be 0x958 and 0x95c?

**Comment by martingkelly** [comment]
I believe you are right for the most recent kernel version. However, for the version I based on (November 7, 2015), the device tree settings were a little different, such that an offset of 0x800 was being added to each of those values. The Free Electrons lab in older versions stated the following:

```
i2c1_pins: pinmux_i2c1_pins {
pinctrl-single,pins = <
0x158 (PIN_INPUT_PULLUP | MUX_MODE2)
0x15c (PIN_INPUT_PULLUP | MUX_MODE2)
>;
};
/* spi0_d1.i2c1_sda */
/* spi0_cs0.i2c1_scl */
That’s surprising: we have 0x158 instead of 0x958 and 0x15c instead of 0x95c! In both cases,
there is a 0x800 offset.
However, this makes sense if you look at the way the base address of the Control Module
Registers is defined. Look for pinctrl-single in arch/arm/boot/dts/am33xx.dtsi:
am33xx_pinmux: pinmux@800 {
compatible = ”pinctrl-single”;
reg = <0x800 0x238>;
#address-cells = <1>;
#size-cells = <0>;
pinctrl-single,register-width = <32>;
pinctrl-single,function-mask = <0x7f>;
};
We first have to compute the absolute address of the above node. It is at offset 800 inside node
scm@210000 inside node l4_wkup@44c00000. So, the absolute address is:
0x44c00000 + 0x210000 + 0x800 = 0x44e10800
So, the base address is 0x44e10800 instead of 0x44e10000 in the datasheet! The value in the
DTS is 0x800 greater, which matches the difference in the offsets.
Why this difference? If you get back to the big TRM document where the offsets are defined,
you will see that below the 0x800 offset, there are many other registers that seem to have nothing
to do with pin muxing. Therefore, starting at offset 0x800 is probably a way to make sure that
using the pinctrl-single driver, users can only access real pin muxing registers and do not
mess with lower registers by mistake.
```

**Comment by Tibalt** [comment]
Thanks for the clarification. Recently I am going through the labs
materials from free electrons. Your repository is very helpful.  Is that
done by yourself? There is another driver example for UART, do you know
where to get the complete code?


Many thanks!

2017-02-19 4:00 GMT+08:00 Martin Kelly <notifications@github.com>:

**Comment by martingkelly** [comment]
Yes, I wrote it myself, following along with the very same Free Electrons lab :). I love that Free Electrons publishes their classes for free; they have been very helpful for me.

As it turns out, you are in luck, as I also did the Free Electrons UART lab! My code is below:
https://github.com/martingkelly/feserial

**Comment by Tibalt** [comment]
today is my lucky day! Thanks!

2017-02-20 8:49 GMT+08:00 Martin Kelly <notifications@github.com>:
